//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sift
{
    
    
    public partial class PaymentMethod : SiftEntity
    {
    }
}
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.12.5.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Sift
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.12.5.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class PaymentMethod 
    {
        [Newtonsoft.Json.JsonProperty("$payment_type", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string payment_type { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$payment_gateway", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string payment_gateway { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$card_bin", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string card_bin { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$card_last4", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string card_last4 { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$avs_result_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string avs_result_code { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$cvv_result_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string cvv_result_code { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$verification_status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string verification_status { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$routing_number", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string routing_number { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$decline_reason_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string decline_reason_code { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$paypal_payer_id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string paypal_payer_id { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$paypal_payer_email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string paypal_payer_email { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$paypal_payer_status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string paypal_payer_status { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$paypal_address_status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string paypal_address_status { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$paypal_protection_eligibility", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string paypal_protection_eligibility { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$paypal_payment_status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string paypal_payment_status { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$stripe_cvc_check", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string stripe_cvc_check { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$stripe_address_line1_check", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string stripe_address_line1_check { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$stripe_address_line2_check", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string stripe_address_line2_check { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$stripe_address_zip_check", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string stripe_address_zip_check { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$stripe_funding", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string stripe_funding { get; set; }
    
        [Newtonsoft.Json.JsonProperty("$stripe_brand", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string stripe_brand { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static PaymentMethod FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<PaymentMethod>(data);
        }
    
    }
}