name: ciworkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Setting an environment variable with the value of a configuration variable
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x.x
      - name: build
        run: |
          ./build.sh --target=restore
          ./build.sh --target=generate
          ./build.sh --target=build
          ./build.sh --target=test

  siftDotNetIntegrationTest:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x.x
      - name: siftDotNetIntegrationTest
        run: |
          ./build.sh --target=restore
          ./build.sh --target=generate
          ./build.sh --target=build
          ./build.sh --target=testNet --filter=Account
          ./build.sh --target=testNet --filter=Cart
          ./build.sh --target=testNet --filter=Chargebacks
          ./build.sh --target=testNet --filter=Contents
          ./build.sh --target=testNet --filter=LoginLogout
          ./build.sh --target=testNet --filter=Notifications
          ./build.sh --target=testNet --filter=Order
          ./build.sh --target=testNet --filter=Passwords
          ./build.sh --target=testNet --filter=Promotions
          ./build.sh --target=testNet --filter=Sessions
          ./build.sh --target=testNet --filter=Transactions
          ./build.sh --target=testNet --filter=Verifications
          ./build.sh --target=testNet --filter=DecisionsRequests
          ./build.sh --target=testNet --filter=Labels
          ./build.sh --target=testNet --filter=MerchantRequests
          ./build.sh --target=testNet --filter=Scores
          ./build.sh --target=testNet --filter=VerificationsRequests
