name: ciworkflow

on:
  push:
    branches: [ "CI-16184" ]
  pull_request:
    branches: [ "CI-16184" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x.x
      - name: Install unzip
        run: |
          sudo apt-get update  
          sudo apt-get install -y unzip
      - name: Install OpenSSH and Git
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client git
      - name: siftDotNetIntegrationTest
        run: |
          ./build.sh --target=restore
          ./build.sh --target=generate
          ./build.sh --target=build
          ./build.sh --target=test
          ./build.sh --target=testNet7 --filter=Account
          ./build.sh --target=testNet7 --filter=Cart
          ./build.sh --target=testNet7 --filter=Chargebacks
          ./build.sh --target=testNet7 --filter=Contents
          ./build.sh --target=testNet7 --filter=LoginLogout
          ./build.sh --target=testNet7 --filter=Notifications
          ./build.sh --target=testNet7 --filter=Order
          ./build.sh --target=testNet7 --filter=Passwords
          ./build.sh --target=testNet7 --filter=Promotions
          ./build.sh --target=testNet7 --filter=Sessions
          ./build.sh --target=testNet7 --filter=Transactions
          ./build.sh --target=testNet7 --filter=Verifications
          ./build.sh --target=testNet7 --filter=DecisionsRequests
          ./build.sh --target=testNet7 --filter=Labels
          ./build.sh --target=testNet7 --filter=MerchantRequests
          ./build.sh --target=testNet7 --filter=Scores
          ./build.sh --target=testNet7 --filter=VerificationsRequests
