name: publishing2NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    env:
      SOLUTION: 'Sift.sln'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.x.x
    - name: Build
      run: |
        dotnet --info
        echo $GITHUB_REF_NAME
        bash -x ./build.sh --target=pack
    - name: Publish
      run: dotnet nuget push artifacts\Sift*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
